### ISSUE TITLE
Unexpected/unhandled error when decoding.

### ISSUE THREAD

**Issue by enlightened** [rogusdev/fast32#2]
Hello, I was using this library to check if a number was in base32 using the decode function. 
```rust
fn is_base32_number(s: &str) -> bool {
    match RFC4648.decode(s.as_bytes()) {
        Ok(_) => true,
        Err(_) => false,
    }
}
```

When I pass a string that has a length less than 6 to the function, it panics with a "attempt to subtract with overflow" without throwing a DecodeError, which is caused by the following function: https://github.com/rogusdev/fast32/blob/e9d804855ec8659e056c0e760ba88d8b5c65f6ea/src/base32/alphabet.rs#L154, more specifically where it tries to index `a[len - 6]`.

I made what i feel like is a bandaid fix, but I have only been writing rust for like a week or 2 so I am not sure if it follows the best conventions and guidelines. 

I am sure this is not an intended function of decode method, but from what I have been reading it would follow Rust conventions to make it as safe as possible.

**Comment by rogusdev** [comment]
Can you clarify what kinds of input you are passing to this function? `RFC4648` is a padded alphabet, so you would expect to see strings like `MY======` as in https://github.com/rogusdev/fast32/blob/e9d804855ec8659e056c0e760ba88d8b5c65f6ea/tests/base32.rs#L530 . But if you are trying to check *numbers* rather than arbitrary strings, you shouldn't be using a padded alphabet anyway, you should be using something like `CROCKFORD` or `RFC4648_HEX_NOPAD` .

Your point that perhaps this should be returning a result instead of just panic-ing is certainly valid, but it also sounds like you might be sending invalid input to the function from what you are describing.
